/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  authorName?: string;
  publishedAt?: string;
  excerpt?: string;
  coverImage?: AccessibleImage;
  body?: PortableText;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & AccessibleImage)
  | ({
      _key: string;
    } & AdvertisingBlock)
  | ({
      _key: string;
    } & SplitImageBlock)
  | ({
      _key: string;
    } & HeroBlock)
  | ({
      _key: string;
    } & FeaturesBlock)
>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AccessibleImage = {
  _type: "accessibleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  ariaLabel?: string;
  link?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName?: string;
  content?: string;
  approved?: boolean;
  page?: PageReference;
};

export type SiteHeaderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteHeader";
};

export type SiteFooterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteFooter";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo?: Seo;
  header?: SiteHeaderReference;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & TwoColumnLayout)
    | ({
        _key: string;
      } & AdvertisingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & FeaturesBlock)
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & SearchBlock)
    | ({
        _key: string;
      } & AuthorBioBlock)
    | ({
        _key: string;
      } & SocialShareBlock)
    | ({
        _key: string;
      } & SplitImageBlock)
    | ({
        _key: string;
      } & ArticleListBlock)
  >;
  footer?: SiteFooterReference;
};

export type SiteFooter = {
  _id: string;
  _type: "siteFooter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  backgroundColor?: Color;
  textColor?: Color;
  copyright?: string;
  logos?: Array<
    {
      _key: string;
    } & AccessibleImage
  >;
  footerLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type SiteHeader = {
  _id: string;
  _type: "siteHeader";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  backgroundColor?: Color;
  textColor?: Color;
  backgroundImage?: AccessibleImage;
  logo?: AccessibleImage;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  siteTitle?: string;
  siteDescription?: string;
  menuLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type ArticleListBlock = {
  _type: "articleListBlock";
  title?: string;
  limit?: number;
};

export type SplitImageBlock = {
  _type: "splitImageBlock";
  imagePosition?: "left" | "right";
  image?: AccessibleImage;
  description?: string;
  linkUrl?: string;
};

export type SocialShareBlock = {
  _type: "socialShareBlock";
  platforms?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: AccessibleImage;
};

export type AuthorBioBlock = {
  _type: "authorBioBlock";
  authorName?: string;
  bio?: string;
  avatar?: AccessibleImage;
};

export type SearchBlock = {
  _type: "searchBlock";
  title?: string;
  placeholderText?: string;
};

export type HeroBlock = {
  _type: "heroBlock";
  heroImage?: AccessibleImage;
  pitch?: string;
  answers?: string;
};

export type FeaturesBlock = {
  _type: "featuresBlock";
  title?: string;
  storyPitch?: string;
  featureImage?: AccessibleImage;
};

export type FaqBlock = {
  _type: "faqBlock";
  title?: string;
  questions?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type AdvertisingBlock = {
  _type: "advertisingBlock";
  promotionalImage?: AccessibleImage;
  affiliateLink?: string;
  description?: string;
};

export type TwoColumnLayout = {
  _type: "twoColumnLayout";
  title?: string;
  leftColumn?: Array<
    | ({
        _key: string;
      } & AdvertisingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & FeaturesBlock)
    | ({
        _key: string;
      } & SearchBlock)
    | ({
        _key: string;
      } & AuthorBioBlock)
    | ({
        _key: string;
      } & SocialShareBlock)
    | ({
        _key: string;
      } & ArticleListBlock)
  >;
  rightColumn?: Array<
    | ({
        _key: string;
      } & AdvertisingBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & FeaturesBlock)
    | ({
        _key: string;
      } & SearchBlock)
    | ({
        _key: string;
      } & AuthorBioBlock)
    | ({
        _key: string;
      } & SocialShareBlock)
    | ({
        _key: string;
      } & ArticleListBlock)
  >;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Article
  | PortableText
  | SanityImageAssetReference
  | AccessibleImage
  | Slug
  | PageReference
  | Comment
  | SiteHeaderReference
  | SiteFooterReference
  | Page
  | SiteFooter
  | Color
  | SiteHeader
  | SanityImageCrop
  | SanityImageHotspot
  | Seo
  | ArticleListBlock
  | SplitImageBlock
  | SocialShareBlock
  | AuthorBioBlock
  | SearchBlock
  | HeroBlock
  | FeaturesBlock
  | FaqBlock
  | AdvertisingBlock
  | TwoColumnLayout
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: app/articles/[slug]/page.tsx
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {    title,    authorName,    publishedAt,    excerpt,    body  }
export type ARTICLE_QUERY_RESULT = {
  title: string | null;
  authorName: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  body: PortableText | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    ...,    seo {      ...,      ogImage {        ...,        asset->      }    },    header-> {      ...,      logo {        ...,        asset->      },      favicon {        ...,        asset->      }    },    pageBuilder[] {      ...,      _type == "heroBlock" => {        heroImage {          ...,          asset->        }      },      _type == "featuresBlock" => {        featureImage {          ...,          asset->        }      },      _type == "advertisingBlock" => {        promotionalImage {          ...,          asset->        }      },      _type == "authorBioBlock" => {        avatar {          ...,          asset->        }      },      _type == "socialShareBlock" => {        ogImage {          ...,          asset->        }      },      _type == "splitImageBlock" => {        image {          ...,          asset->        }      },      _type == "twoColumnLayout" => {        ...,        leftColumn[] {          ...,          _type == "featuresBlock" => { featureImage { ..., asset-> } },          _type == "advertisingBlock" => { promotionalImage { ..., asset-> } },          _type == "authorBioBlock" => { avatar { ..., asset-> } },          _type == "socialShareBlock" => { ogImage { ..., asset-> } }        },        rightColumn[] {          ...,          _type == "featuresBlock" => { featureImage { ..., asset-> } },          _type == "advertisingBlock" => { promotionalImage { ..., asset-> } },          _type == "authorBioBlock" => { avatar { ..., asset-> } },          _type == "socialShareBlock" => { ogImage { ..., asset-> } }        }      }    },    footer-> {      ...,      logos[] {        ...,        asset->      }    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo: {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    ogImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex?: boolean;
  } | null;
  header: {
    _id: string;
    _type: "siteHeader";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    backgroundColor?: Color;
    textColor?: Color;
    backgroundImage?: AccessibleImage;
    logo: {
      _type: "accessibleImage";
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      ariaLabel?: string;
      link?: string;
    } | null;
    favicon: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    siteTitle?: string;
    siteDescription?: string;
    menuLinks?: Array<{
      label?: string;
      url?: string;
      _key: string;
    }>;
  } | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "advertisingBlock";
        promotionalImage: {
          _type: "accessibleImage";
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          ariaLabel?: string;
          link?: string;
        } | null;
        affiliateLink?: string;
        description?: string;
      }
    | {
        _key: string;
        _type: "articleListBlock";
        title?: string;
        limit?: number;
      }
    | {
        _key: string;
        _type: "authorBioBlock";
        authorName?: string;
        bio?: string;
        avatar: {
          _type: "accessibleImage";
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          ariaLabel?: string;
          link?: string;
        } | null;
      }
    | {
        _key: string;
        _type: "faqBlock";
        title?: string;
        questions?: Array<{
          question?: string;
          answer?: string;
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "featuresBlock";
        title?: string;
        storyPitch?: string;
        featureImage: {
          _type: "accessibleImage";
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          ariaLabel?: string;
          link?: string;
        } | null;
      }
    | {
        _key: string;
        _type: "heroBlock";
        heroImage: {
          _type: "accessibleImage";
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          ariaLabel?: string;
          link?: string;
        } | null;
        pitch?: string;
        answers?: string;
      }
    | {
        _key: string;
        _type: "searchBlock";
        title?: string;
        placeholderText?: string;
      }
    | {
        _key: string;
        _type: "socialShareBlock";
        platforms?: Array<{
          platform?: string;
          url?: string;
          _key: string;
        }>;
        ogTitle?: string;
        ogDescription?: string;
        ogImage: {
          _type: "accessibleImage";
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          ariaLabel?: string;
          link?: string;
        } | null;
      }
    | {
        _key: string;
        _type: "splitImageBlock";
        imagePosition?: "left" | "right";
        image: {
          _type: "accessibleImage";
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          ariaLabel?: string;
          link?: string;
        } | null;
        description?: string;
        linkUrl?: string;
      }
    | {
        _key: string;
        _type: "twoColumnLayout";
        title?: string;
        leftColumn: Array<
          | {
              _key: string;
              _type: "advertisingBlock";
              promotionalImage: {
                _type: "accessibleImage";
                asset: {
                  _id: string;
                  _type: "sanity.imageAsset";
                  _createdAt: string;
                  _updatedAt: string;
                  _rev: string;
                  originalFilename?: string;
                  label?: string;
                  title?: string;
                  description?: string;
                  altText?: string;
                  sha1hash?: string;
                  extension?: string;
                  mimeType?: string;
                  size?: number;
                  assetId?: string;
                  uploadId?: string;
                  path?: string;
                  url?: string;
                  metadata?: SanityImageMetadata;
                  source?: SanityAssetSourceData;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                ariaLabel?: string;
                link?: string;
              } | null;
              affiliateLink?: string;
              description?: string;
            }
          | {
              _key: string;
              _type: "articleListBlock";
              title?: string;
              limit?: number;
            }
          | {
              _key: string;
              _type: "authorBioBlock";
              authorName?: string;
              bio?: string;
              avatar: {
                _type: "accessibleImage";
                asset: {
                  _id: string;
                  _type: "sanity.imageAsset";
                  _createdAt: string;
                  _updatedAt: string;
                  _rev: string;
                  originalFilename?: string;
                  label?: string;
                  title?: string;
                  description?: string;
                  altText?: string;
                  sha1hash?: string;
                  extension?: string;
                  mimeType?: string;
                  size?: number;
                  assetId?: string;
                  uploadId?: string;
                  path?: string;
                  url?: string;
                  metadata?: SanityImageMetadata;
                  source?: SanityAssetSourceData;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                ariaLabel?: string;
                link?: string;
              } | null;
            }
          | {
              _key: string;
              _type: "faqBlock";
              title?: string;
              questions?: Array<{
                question?: string;
                answer?: string;
                _key: string;
              }>;
            }
          | {
              _key: string;
              _type: "featuresBlock";
              title?: string;
              storyPitch?: string;
              featureImage: {
                _type: "accessibleImage";
                asset: {
                  _id: string;
                  _type: "sanity.imageAsset";
                  _createdAt: string;
                  _updatedAt: string;
                  _rev: string;
                  originalFilename?: string;
                  label?: string;
                  title?: string;
                  description?: string;
                  altText?: string;
                  sha1hash?: string;
                  extension?: string;
                  mimeType?: string;
                  size?: number;
                  assetId?: string;
                  uploadId?: string;
                  path?: string;
                  url?: string;
                  metadata?: SanityImageMetadata;
                  source?: SanityAssetSourceData;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                ariaLabel?: string;
                link?: string;
              } | null;
            }
          | {
              _key: string;
              _type: "searchBlock";
              title?: string;
              placeholderText?: string;
            }
          | {
              _key: string;
              _type: "socialShareBlock";
              platforms?: Array<{
                platform?: string;
                url?: string;
                _key: string;
              }>;
              ogTitle?: string;
              ogDescription?: string;
              ogImage: {
                _type: "accessibleImage";
                asset: {
                  _id: string;
                  _type: "sanity.imageAsset";
                  _createdAt: string;
                  _updatedAt: string;
                  _rev: string;
                  originalFilename?: string;
                  label?: string;
                  title?: string;
                  description?: string;
                  altText?: string;
                  sha1hash?: string;
                  extension?: string;
                  mimeType?: string;
                  size?: number;
                  assetId?: string;
                  uploadId?: string;
                  path?: string;
                  url?: string;
                  metadata?: SanityImageMetadata;
                  source?: SanityAssetSourceData;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                ariaLabel?: string;
                link?: string;
              } | null;
            }
        > | null;
        rightColumn: Array<
          | {
              _key: string;
              _type: "advertisingBlock";
              promotionalImage: {
                _type: "accessibleImage";
                asset: {
                  _id: string;
                  _type: "sanity.imageAsset";
                  _createdAt: string;
                  _updatedAt: string;
                  _rev: string;
                  originalFilename?: string;
                  label?: string;
                  title?: string;
                  description?: string;
                  altText?: string;
                  sha1hash?: string;
                  extension?: string;
                  mimeType?: string;
                  size?: number;
                  assetId?: string;
                  uploadId?: string;
                  path?: string;
                  url?: string;
                  metadata?: SanityImageMetadata;
                  source?: SanityAssetSourceData;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                ariaLabel?: string;
                link?: string;
              } | null;
              affiliateLink?: string;
              description?: string;
            }
          | {
              _key: string;
              _type: "articleListBlock";
              title?: string;
              limit?: number;
            }
          | {
              _key: string;
              _type: "authorBioBlock";
              authorName?: string;
              bio?: string;
              avatar: {
                _type: "accessibleImage";
                asset: {
                  _id: string;
                  _type: "sanity.imageAsset";
                  _createdAt: string;
                  _updatedAt: string;
                  _rev: string;
                  originalFilename?: string;
                  label?: string;
                  title?: string;
                  description?: string;
                  altText?: string;
                  sha1hash?: string;
                  extension?: string;
                  mimeType?: string;
                  size?: number;
                  assetId?: string;
                  uploadId?: string;
                  path?: string;
                  url?: string;
                  metadata?: SanityImageMetadata;
                  source?: SanityAssetSourceData;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                ariaLabel?: string;
                link?: string;
              } | null;
            }
          | {
              _key: string;
              _type: "faqBlock";
              title?: string;
              questions?: Array<{
                question?: string;
                answer?: string;
                _key: string;
              }>;
            }
          | {
              _key: string;
              _type: "featuresBlock";
              title?: string;
              storyPitch?: string;
              featureImage: {
                _type: "accessibleImage";
                asset: {
                  _id: string;
                  _type: "sanity.imageAsset";
                  _createdAt: string;
                  _updatedAt: string;
                  _rev: string;
                  originalFilename?: string;
                  label?: string;
                  title?: string;
                  description?: string;
                  altText?: string;
                  sha1hash?: string;
                  extension?: string;
                  mimeType?: string;
                  size?: number;
                  assetId?: string;
                  uploadId?: string;
                  path?: string;
                  url?: string;
                  metadata?: SanityImageMetadata;
                  source?: SanityAssetSourceData;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                ariaLabel?: string;
                link?: string;
              } | null;
            }
          | {
              _key: string;
              _type: "searchBlock";
              title?: string;
              placeholderText?: string;
            }
          | {
              _key: string;
              _type: "socialShareBlock";
              platforms?: Array<{
                platform?: string;
                url?: string;
                _key: string;
              }>;
              ogTitle?: string;
              ogDescription?: string;
              ogImage: {
                _type: "accessibleImage";
                asset: {
                  _id: string;
                  _type: "sanity.imageAsset";
                  _createdAt: string;
                  _updatedAt: string;
                  _rev: string;
                  originalFilename?: string;
                  label?: string;
                  title?: string;
                  description?: string;
                  altText?: string;
                  sha1hash?: string;
                  extension?: string;
                  mimeType?: string;
                  size?: number;
                  assetId?: string;
                  uploadId?: string;
                  path?: string;
                  url?: string;
                  metadata?: SanityImageMetadata;
                  source?: SanityAssetSourceData;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                ariaLabel?: string;
                link?: string;
              } | null;
            }
        > | null;
      }
  > | null;
  footer: {
    _id: string;
    _type: "siteFooter";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    backgroundColor?: Color;
    textColor?: Color;
    copyright?: string;
    logos: Array<{
      _key: string;
      _type: "accessibleImage";
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      ariaLabel?: string;
      link?: string;
    }> | null;
    footerLinks?: Array<{
      label?: string;
      url?: string;
      _key: string;
    }>;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "article" && slug.current == $slug][0] {\n    title,\n    authorName,\n    publishedAt,\n    excerpt,\n    body\n  }\n': ARTICLE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    ...,\n    seo {\n      ...,\n      ogImage {\n        ...,\n        asset->\n      }\n    },\n    header-> {\n      ...,\n      logo {\n        ...,\n        asset->\n      },\n      favicon {\n        ...,\n        asset->\n      }\n    },\n    pageBuilder[] {\n      ...,\n      _type == "heroBlock" => {\n        heroImage {\n          ...,\n          asset->\n        }\n      },\n      _type == "featuresBlock" => {\n        featureImage {\n          ...,\n          asset->\n        }\n      },\n      _type == "advertisingBlock" => {\n        promotionalImage {\n          ...,\n          asset->\n        }\n      },\n      _type == "authorBioBlock" => {\n        avatar {\n          ...,\n          asset->\n        }\n      },\n      _type == "socialShareBlock" => {\n        ogImage {\n          ...,\n          asset->\n        }\n      },\n      _type == "splitImageBlock" => {\n        image {\n          ...,\n          asset->\n        }\n      },\n      _type == "twoColumnLayout" => {\n        ...,\n        leftColumn[] {\n          ...,\n          _type == "featuresBlock" => { featureImage { ..., asset-> } },\n          _type == "advertisingBlock" => { promotionalImage { ..., asset-> } },\n          _type == "authorBioBlock" => { avatar { ..., asset-> } },\n          _type == "socialShareBlock" => { ogImage { ..., asset-> } }\n        },\n        rightColumn[] {\n          ...,\n          _type == "featuresBlock" => { featureImage { ..., asset-> } },\n          _type == "advertisingBlock" => { promotionalImage { ..., asset-> } },\n          _type == "authorBioBlock" => { avatar { ..., asset-> } },\n          _type == "socialShareBlock" => { ogImage { ..., asset-> } }\n        }\n      }\n    },\n    footer-> {\n      ...,\n      logos[] {\n        ...,\n        asset->\n      }\n    }\n  }\n': PAGE_QUERY_RESULT;
  }
}
