installed_at: '2026-06-19T04:48:52+00:00'
skill_id: git/mastering-typescript
git_repo: https://github.com/SpillwaveSolutions/mastering-typescript-skill
skill_path: C:\Users\manag\AppData\Local\Temp\skilz-git-c0z1kx3u\mastering-typescript
git_sha: 2f74a00f731f2ea4d48f45d852067a7be8efd0d1
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
